export const sampleCars = [
  {
    _id: "car-honda-city",
    make: "Honda",
    model: "City",
    name: "Honda City",
    slug: "honda-city-zx-cvt",
    variant: "ZX CVT",
    summary:
      "A refined sedan for buyers who want comfort, safety, boot space, and easy city manners.",
    bodyType: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    startingPrice: 1208000,
    priceRange: { min: 1208000, max: 1620000 },
    mileage: 18.4,
    safetyRating: 5,
    userRating: 4.5,
    reviewCount: 128,
    images: [
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "1.5L i-VTEC petrol",
      power: "119 bhp",
      torque: "145 Nm",
      drivetrain: "FWD",
      bootSpace: "506 L",
      groundClearance: "165 mm",
      airbags: 6,
      infotainment: "8-inch touchscreen",
      keyFeatures: ["ADAS", "Sunroof", "Lane watch camera", "Connected car tech"],
    },
    pros: [
      "Comfortable rear seat and big boot",
      "Smooth CVT for city driving",
      "Strong safety package",
    ],
    cons: ["No diesel option", "Ground clearance is modest"],
    tags: ["city", "comfort", "safety", "family", "features"],
    variants: [
      {
        _id: "variant-city-v-mt",
        name: "V MT",
        price: 1208000,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: 17.8,
        engine: "1.5L petrol",
        features: ["LED headlamps", "Cruise control"],
      },
      {
        _id: "variant-city-zx-cvt",
        name: "ZX CVT",
        price: 1620000,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: 18.4,
        engine: "1.5L petrol",
        features: ["ADAS", "Sunroof", "6 airbags"],
      },
    ],
  },
  {
    _id: "car-hyundai-creta",
    make: "Hyundai",
    model: "Creta",
    name: "Hyundai Creta",
    slug: "hyundai-creta-sx-o",
    variant: "SX(O)",
    summary:
      "A feature-rich compact SUV with wide powertrain choice and easy ownership.",
    bodyType: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    startingPrice: 1100000,
    priceRange: { min: 1100000, max: 2020000 },
    mileage: 17.4,
    safetyRating: 4,
    userRating: 4.4,
    reviewCount: 211,
    images: [
      "https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "1.5L petrol / turbo petrol / diesel",
      power: "113-158 bhp",
      torque: "144-253 Nm",
      drivetrain: "FWD",
      bootSpace: "433 L",
      groundClearance: "190 mm",
      airbags: 6,
      infotainment: "10.25-inch touchscreen",
      keyFeatures: ["Panoramic sunroof", "Ventilated seats", "ADAS", "360 camera"],
    },
    pros: [
      "Very broad variant and engine range",
      "Loaded cabin feels premium",
      "Easy to drive in traffic",
    ],
    cons: ["Top variants are expensive", "Ride can feel firm on bad roads"],
    tags: ["features", "city", "family", "automatic", "premium"],
    variants: [
      {
        _id: "variant-creta-ex",
        name: "EX Petrol",
        price: 1221000,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: 17.4,
        engine: "1.5L petrol",
        features: ["6 airbags", "Rear AC vents"],
      },
      {
        _id: "variant-creta-sxo",
        name: "SX(O) Turbo DCT",
        price: 2020000,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: 18.2,
        engine: "1.5L turbo petrol",
        features: ["ADAS", "Ventilated seats", "Panoramic sunroof"],
      },
    ],
  },
  {
    _id: "car-tata-nexon",
    make: "Tata",
    model: "Nexon",
    name: "Tata Nexon",
    slug: "tata-nexon-fearless-plus",
    variant: "Fearless Plus",
    summary:
      "A safety-first compact SUV with strong road presence, many features, and petrol, diesel, and EV choices.",
    bodyType: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    startingPrice: 815000,
    priceRange: { min: 815000, max: 1560000 },
    mileage: 17.8,
    safetyRating: 5,
    userRating: 4.3,
    reviewCount: 189,
    images: [
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "1.2L turbo petrol / 1.5L diesel",
      power: "113-118 bhp",
      torque: "170-260 Nm",
      drivetrain: "FWD",
      bootSpace: "382 L",
      groundClearance: "208 mm",
      airbags: 6,
      infotainment: "10.25-inch touchscreen",
      keyFeatures: ["5-star safety", "Ventilated seats", "360 camera", "Connected tech"],
    },
    pros: [
      "Excellent safety rating",
      "High ground clearance",
      "Multiple fuel and gearbox options",
    ],
    cons: ["Rear seat width is average", "AMT can feel slow"],
    tags: ["safety", "value", "family", "highway", "features"],
    variants: [
      {
        _id: "variant-nexon-smart",
        name: "Smart Petrol",
        price: 815000,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: 17.4,
        engine: "1.2L turbo petrol",
        features: ["6 airbags", "ESP"],
      },
      {
        _id: "variant-nexon-fearless",
        name: "Fearless Plus DCA",
        price: 1420000,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: 17.8,
        engine: "1.2L turbo petrol",
        features: ["360 camera", "Ventilated seats", "Sunroof"],
      },
    ],
  },
  {
    _id: "car-mahindra-xuv700",
    make: "Mahindra",
    model: "XUV700",
    name: "Mahindra XUV700",
    slug: "mahindra-xuv700-ax7",
    variant: "AX7",
    summary:
      "A powerful family SUV with seven seats, strong safety credentials, and highway-friendly performance.",
    bodyType: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    seatingCapacity: 7,
    startingPrice: 1399000,
    priceRange: { min: 1399000, max: 2699000 },
    mileage: 16.6,
    safetyRating: 5,
    userRating: 4.6,
    reviewCount: 246,
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "2.0L turbo petrol / 2.2L diesel",
      power: "153-197 bhp",
      torque: "360-450 Nm",
      drivetrain: "FWD / AWD",
      bootSpace: "240 L with all rows up",
      groundClearance: "200 mm",
      airbags: 7,
      infotainment: "Dual 10.25-inch screens",
      keyFeatures: ["ADAS", "Panoramic sunroof", "Sony audio", "AWD option"],
    },
    pros: [
      "Strong engines for highway use",
      "Excellent safety and ADAS suite",
      "Flexible 7-seat layout",
    ],
    cons: ["Third-row luggage space is limited", "Top trims stretch the budget"],
    tags: ["family", "highway", "safety", "performance", "seven-seater"],
    variants: [
      {
        _id: "variant-xuv700-mx",
        name: "MX Petrol",
        price: 1399000,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: 15,
        engine: "2.0L turbo petrol",
        features: ["7-inch cluster", "ESP"],
      },
      {
        _id: "variant-xuv700-ax7-diesel",
        name: "AX7 Diesel AT",
        price: 2459000,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: 16.6,
        engine: "2.2L diesel",
        features: ["ADAS", "Panoramic sunroof", "7 airbags"],
      },
    ],
  },
  {
    _id: "car-maruti-baleno",
    make: "Maruti Suzuki",
    model: "Baleno",
    name: "Maruti Suzuki Baleno",
    slug: "maruti-suzuki-baleno-alpha",
    variant: "Alpha AMT",
    summary:
      "A practical premium hatchback with excellent efficiency, low running costs, and wide service reach.",
    bodyType: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    startingPrice: 666000,
    priceRange: { min: 666000, max: 988000 },
    mileage: 22.9,
    safetyRating: 3,
    userRating: 4.1,
    reviewCount: 173,
    images: [
      "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "1.2L petrol",
      power: "88 bhp",
      torque: "113 Nm",
      drivetrain: "FWD",
      bootSpace: "318 L",
      groundClearance: "170 mm",
      airbags: 6,
      infotainment: "9-inch touchscreen",
      keyFeatures: ["360 camera", "Head-up display", "Auto climate control"],
    },
    pros: [
      "Excellent mileage and low maintenance",
      "Spacious cabin for a hatchback",
      "Easy to park and drive",
    ],
    cons: ["Safety rating trails rivals", "AMT is not as smooth as CVT/DCT"],
    tags: ["value", "mileage", "city", "low-maintenance"],
    variants: [
      {
        _id: "variant-baleno-delta",
        name: "Delta MT",
        price: 745000,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: 22.3,
        engine: "1.2L petrol",
        features: ["7-inch touchscreen", "ESP"],
      },
      {
        _id: "variant-baleno-alpha-amt",
        name: "Alpha AMT",
        price: 988000,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: 22.9,
        engine: "1.2L petrol",
        features: ["360 camera", "HUD", "LED projector lamps"],
      },
    ],
  },
  {
    _id: "car-toyota-innova-hycross",
    make: "Toyota",
    model: "Innova Hycross",
    name: "Toyota Innova Hycross",
    slug: "toyota-innova-hycross-zx",
    variant: "ZX Hybrid",
    summary:
      "A premium three-row family MPV with hybrid efficiency, space, comfort, and strong long-term ownership.",
    bodyType: "MPV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    seatingCapacity: 7,
    startingPrice: 1982000,
    priceRange: { min: 1982000, max: 3070000 },
    mileage: 23.2,
    safetyRating: 5,
    userRating: 4.7,
    reviewCount: 151,
    images: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "2.0L petrol hybrid",
      power: "183 bhp combined",
      torque: "188 Nm",
      drivetrain: "FWD",
      bootSpace: "300 L with all rows up",
      groundClearance: "185 mm",
      airbags: 6,
      infotainment: "10.1-inch touchscreen",
      keyFeatures: ["Ottoman seats", "ADAS", "Hybrid powertrain", "Panoramic sunroof"],
    },
    pros: [
      "Excellent family comfort",
      "Hybrid efficiency is strong for its size",
      "Toyota reliability and resale value",
    ],
    cons: ["Expensive top trims", "No diesel/manual option"],
    tags: ["family", "mileage", "comfort", "hybrid", "seven-seater"],
    variants: [
      {
        _id: "variant-hycross-gx",
        name: "GX Petrol",
        price: 1982000,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: 16.1,
        engine: "2.0L petrol",
        features: ["8 seats", "LED headlamps"],
      },
      {
        _id: "variant-hycross-zx",
        name: "ZX Hybrid",
        price: 3070000,
        fuelType: "Hybrid",
        transmission: "Automatic",
        mileage: 23.2,
        engine: "2.0L hybrid",
        features: ["Ottoman seats", "ADAS", "Panoramic sunroof"],
      },
    ],
  },
  {
    _id: "car-kia-seltos",
    make: "Kia",
    model: "Seltos",
    name: "Kia Seltos",
    slug: "kia-seltos-gtx-plus",
    variant: "GTX Plus DCT",
    summary:
      "A polished compact SUV with premium cabin tech, punchy turbo performance, and a broad variant range.",
    bodyType: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    startingPrice: 1090000,
    priceRange: { min: 1090000, max: 2035000 },
    mileage: 17.9,
    safetyRating: 4,
    userRating: 4.4,
    reviewCount: 198,
    images: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "1.5L petrol / turbo petrol / diesel",
      power: "113-158 bhp",
      torque: "144-253 Nm",
      drivetrain: "FWD",
      bootSpace: "433 L",
      groundClearance: "190 mm",
      airbags: 6,
      infotainment: "10.25-inch touchscreen",
      keyFeatures: ["ADAS", "Bose audio", "Ventilated seats", "Dual-zone climate"],
    },
    pros: [
      "Premium cabin experience",
      "Turbo DCT is quick and smooth",
      "Loaded feature list",
    ],
    cons: ["Ride can feel busy", "Top trims are costly"],
    tags: ["features", "premium", "performance", "city", "highway"],
    variants: [
      {
        _id: "variant-seltos-htk",
        name: "HTK Petrol",
        price: 1220000,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: 17.7,
        engine: "1.5L petrol",
        features: ["6 airbags", "8-inch touchscreen"],
      },
      {
        _id: "variant-seltos-gtx",
        name: "GTX Plus DCT",
        price: 2035000,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: 17.9,
        engine: "1.5L turbo petrol",
        features: ["ADAS", "Bose audio", "Ventilated seats"],
      },
    ],
  },
  {
    _id: "car-mg-comet",
    make: "MG",
    model: "Comet EV",
    name: "MG Comet EV",
    slug: "mg-comet-ev-exclusive",
    variant: "Exclusive",
    summary:
      "A compact city EV for short daily commutes, tight parking, and low running costs.",
    bodyType: "Hatchback",
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 4,
    startingPrice: 699000,
    priceRange: { min: 699000, max: 958000 },
    mileage: 230,
    safetyRating: 3,
    userRating: 4,
    reviewCount: 74,
    images: [
      "https://images.unsplash.com/photo-1593941707882-a5bba53b0998?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
    ],
    specs: {
      engine: "17.3 kWh battery",
      power: "41 bhp",
      torque: "110 Nm",
      drivetrain: "RWD",
      bootSpace: "Compact city boot",
      groundClearance: "165 mm",
      airbags: 2,
      infotainment: "Dual 10.25-inch screens",
      keyFeatures: ["Connected tech", "Compact footprint", "Low running cost"],
    },
    pros: [
      "Very easy to park",
      "Low urban running cost",
      "Quirky and modern cabin",
    ],
    cons: ["Not ideal as a primary family car", "Limited highway comfort"],
    tags: ["city", "electric", "value", "commute", "low-maintenance"],
    variants: [
      {
        _id: "variant-comet-pace",
        name: "Pace",
        price: 699000,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: 230,
        engine: "17.3 kWh battery",
        features: ["LED lighting", "Connected car basics"],
      },
      {
        _id: "variant-comet-exclusive",
        name: "Exclusive",
        price: 958000,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: 230,
        engine: "17.3 kWh battery",
        features: ["Dual screens", "Wireless Android Auto and Apple CarPlay"],
      },
    ],
  },
];

export const sampleReviews = [
  {
    _id: "review-city-1",
    car: "car-honda-city",
    userName: "Ritika S.",
    rating: 5,
    title: "Relaxed daily sedan",
    comment:
      "The cabin is calm, the CVT is smooth, and my parents love the rear seat comfort.",
    ownershipPeriod: "8 months",
    pros: ["Comfort", "Boot space"],
    cons: ["Low ground clearance"],
    status: "approved",
    createdAt: "2026-01-20T10:00:00.000Z",
  },
  {
    _id: "review-creta-1",
    car: "car-hyundai-creta",
    userName: "Aditya M.",
    rating: 4,
    title: "Feature packed and easy",
    comment:
      "Bought it for mixed city and highway use. The cabin features make every drive feel premium.",
    ownershipPeriod: "1 year",
    pros: ["Features", "Automatic gearbox"],
    cons: ["Pricey top trims"],
    status: "approved",
    createdAt: "2026-02-04T10:00:00.000Z",
  },
  {
    _id: "review-nexon-1",
    car: "car-tata-nexon",
    userName: "Kabir P.",
    rating: 4,
    title: "Safety confidence",
    comment:
      "I shortlisted it mainly for safety and ground clearance. It feels solid on broken roads.",
    ownershipPeriod: "6 months",
    pros: ["Safety", "Ground clearance"],
    cons: ["Rear seat width"],
    status: "approved",
    createdAt: "2026-03-10T10:00:00.000Z",
  },
  {
    _id: "review-xuv700-1",
    car: "car-mahindra-xuv700",
    userName: "Neha R.",
    rating: 5,
    title: "Best highway family car",
    comment:
      "The diesel automatic is effortless on long trips and the ADAS suite reduces fatigue.",
    ownershipPeriod: "1.5 years",
    pros: ["Performance", "Safety", "Space"],
    cons: ["Boot with third row"],
    status: "approved",
    createdAt: "2026-04-11T10:00:00.000Z",
  },
];

export const sampleAdmin = {
  _id: "admin-demo",
  name: "CarWise Admin",
  email: process.env.SEED_ADMIN_EMAIL || "admin@carwise.dev",
  password: process.env.SEED_ADMIN_PASSWORD || "Admin@1234",
  role: "admin",
};
